build: false

clone_depth: 1

environment:
  matrix:
    - nodejs_version: 9
    - nodejs_version: 8
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - npm --version
  - yarn --version
  - npm test
