# https://github.com/sasstools/sass-lint/#files
files:
  include: '**/*.+(sass|scss)'

# https://github.com/sasstools/sass-lint/#options
options:
  merge-default-rules: false
  formatter: stylish

# https://github.com/sasstools/sass-lint/tree/master/docs/rules
rules:

  attribute-quotes:
    - 2
    -
      include: true

  bem-depth:
    - 2
    -
      max-depth: 1

  border-zero:
    - 2
    -
      convention: '0'

  brace-style:
    - 2
    -
      style: '1tbs'
      allow-single-line: true

  class-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
      ignore: []

  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false

  declarations-before-nesting: 2

  empty-args:
    - 2
    -
      include: false

  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: true

  extends-before-declarations: 2

  extends-before-mixins: 2

  final-newline:
    - 2
    -
      include: true

  force-attribute-nesting: 2

  force-element-nesting: 2

  force-pseudo-nesting: 2

  function-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'

  hex-length:
    - 2
    -
      style: 'short'

  hex-notation:
    - 2
    -
      style: 'lowercase'

  id-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
      ignore: []

  indentation:
    - 2
    -
      size: 4

  leading-zero:
    - 2
    -
      include: false

  max-file-line-count:
    - 2
    -
      length: 300

  max-line-length:
    - 2
    -
      length: 120

  mixin-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'

  mixins-before-declarations:
    - 2
    -
      exclude: ['breakpoint', 'mq']

  nesting-depth:
    - 2
    -
      max-depth: 4

  no-attribute-selectors: 2

  no-color-hex: 0

  no-color-keywords: 2

  no-color-literals:
    - 2
    -
      allow-map-identifiers: true
      allow-rgba: false
      allow-variable-identifiers: true

  no-combinators: 0

  no-css-comments: 2

  no-debug: 2

  no-disallowed-properties: 0

  no-duplicate-properties:
    - 2
    -
      exclude: []

  no-empty-rulesets: 2

  no-extends: 0

  no-ids: 2

  no-important: 0

  no-invalid-hex: 2

  no-mergeable-selectors:
    - 2
    -
      whitelist: []

  no-misspelled-properties:
    - 2
    -
      extra-properties: []

  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false

  no-trailing-whitespace: 2

  no-trailing-zero: 2

  no-transition-all: 2

  no-universal-selectors: 2

  no-url-domains: 2

  no-url-protocols: 2

  no-vendor-prefixes:
    - 2
    -
      additional-identifiers: []
      excluded-identifiers: []
      ignore-non-standard: false

  no-warn: 2

  one-declaration-per-line: 2

  placeholder-in-extend: 2

  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'

  property-sort-order:
    - 2
    -
      ignore-custom-properties: false
      order:
        - font
        - font-family
        - font-size
        - font-weight
        - font-style
        - font-variant
        - font-size-adjust
        - font-stretch
        - font-effect
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - font-smooth
        - line-height
        -
        - position
        - z-index
        - top
        - right
        - bottom
        - left
        -
        - display
        - visibility
        - float
        - clear
        - overflow
        - overflow-x
        - overflow-y
        - -ms-overflow-x
        - -ms-overflow-y
        - clip
        - zoom
        - flex-direction
        - flex-order
        - flex-pack
        - flex-align
        -
        - -webkit-box-sizing
        - -moz-box-sizing
        - box-sizing
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        -
        - table-layout
        - empty-cells
        - caption-side
        - border-spacing
        - border-collapse
        - list-style
        - list-style-position
        - list-style-type
        - list-style-image
        -
        - content
        - quotes
        - counter-reset
        - counter-increment
        - resize
        - cursor
        - -webkit-user-select
        - -moz-user-select
        - -ms-user-select
        - user-select
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
        - -webkit-transition
        - -moz-transition
        - -ms-transition
        - -o-transition
        - transition
        - -webkit-transition-delay
        - -moz-transition-delay
        - -ms-transition-delay
        - -o-transition-delay
        - transition-delay
        - -webkit-transition-timing-function
        - -moz-transition-timing-function
        - -ms-transition-timing-function
        - -o-transition-timing-function
        - transition-timing-function
        - -webkit-transition-duration
        - -moz-transition-duration
        - -ms-transition-duration
        - -o-transition-duration
        - transition-duration
        - -webkit-transition-property
        - -moz-transition-property
        - -ms-transition-property
        - -o-transition-property
        - transition-property
        - -webkit-transform
        - -moz-transform
        - -ms-transform
        - -o-transform
        - transform
        - -webkit-transform-origin
        - -moz-transform-origin
        - -ms-transform-origin
        - -o-transform-origin
        - transform-origin
        - -webkit-animation
        - -moz-animation
        - -ms-animation
        - -o-animation
        - animation
        - -webkit-animation-name
        - -moz-animation-name
        - -ms-animation-name
        - -o-animation-name
        - animation-name
        - -webkit-animation-duration
        - -moz-animation-duration
        - -ms-animation-duration
        - -o-animation-duration
        - animation-duration
        - -webkit-animation-play-state
        - -moz-animation-play-state
        - -ms-animation-play-state
        - -o-animation-play-state
        - animation-play-state
        - -webkit-animation-timing-function
        - -moz-animation-timing-function
        - -ms-animation-timing-function
        - -o-animation-timing-function
        - animation-timing-function
        - -webkit-animation-delay
        - -moz-animation-delay
        - -ms-animation-delay
        - -o-animation-delay
        - animation-delay
        - -webkit-animation-iteration-count
        - -moz-animation-iteration-count
        - -ms-animation-iteration-count
        - -o-animation-iteration-count
        - animation-iteration-count
        - -webkit-animation-direction
        - -moz-animation-direction
        - -ms-animation-direction
        - -o-animation-direction
        - animation-direction
        - text-align
        - -webkit-text-align-last
        - -moz-text-align-last
        - -ms-text-align-last
        - text-align-last
        - vertical-align
        - white-space
        - text-decoration
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-style
        - text-emphasis-position
        - text-indent
        - -ms-text-justify
        - text-justify
        - letter-spacing
        - word-spacing
        - -ms-writing-mode
        - text-outline
        - text-transform
        - text-wrap
        - text-overflow
        - -ms-text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - -ms-word-wrap
        - word-wrap
        - word-break
        - -ms-word-break
        - -moz-tab-size
        - -o-tab-size
        - tab-size
        - -webkit-hyphens
        - -moz-hyphens
        - hyphens
        - pointer-events
        -
        - opacity
        - filter:progid:DXImageTransform.Microsoft.Alpha(Opacity
        - -ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha
        - -ms-interpolation-mode
        - color
        - border
        - border-width
        - border-style
        - border-color
        - border-top
        - border-top-width
        - border-top-style
        - border-top-color
        - border-right
        - border-right-width
        - border-right-style
        - border-right-color
        - border-bottom
        - border-bottom-width
        - border-bottom-style
        - border-bottom-color
        - border-left
        - border-left-width
        - border-left-style
        - border-left-color
        - -webkit-border-radius
        - -moz-border-radius
        - border-radius
        - -webkit-border-top-left-radius
        - -moz-border-radius-topleft
        - border-top-left-radius
        - -webkit-border-top-right-radius
        - -moz-border-radius-topright
        - border-top-right-radius
        - -webkit-border-bottom-right-radius
        - -moz-border-radius-bottomright
        - border-bottom-right-radius
        - -webkit-border-bottom-left-radius
        - -moz-border-radius-bottomleft
        - border-bottom-left-radius
        - -webkit-border-image
        - -moz-border-image
        - -o-border-image
        - border-image
        - -webkit-border-image-source
        - -moz-border-image-source
        - -o-border-image-source
        - border-image-source
        - -webkit-border-image-slice
        - -moz-border-image-slice
        - -o-border-image-slice
        - border-image-slice
        - -webkit-border-image-width
        - -moz-border-image-width
        - -o-border-image-width
        - border-image-width
        - -webkit-border-image-outset
        - -moz-border-image-outset
        - -o-border-image-outset
        - border-image-outset
        - -webkit-border-image-repeat
        - -moz-border-image-repeat
        - -o-border-image-repeat
        - border-image-repeat
        - outline
        - outline-width
        - outline-style
        - outline-color
        - outline-offset
        - background
        - filter:progid:DXImageTransform.Microsoft.AlphaImageLoader
        - background-color
        - background-image
        - background-repeat
        - background-attachment
        - background-position
        - background-position-x
        - -ms-background-position-x
        - background-position-y
        - -ms-background-position-y
        - -webkit-background-clip
        - -moz-background-clip
        - background-clip
        - background-origin
        - -webkit-background-size
        - -moz-background-size
        - -o-background-size
        - background-size
        - box-decoration-break
        - -webkit-box-shadow
        - -moz-box-shadow
        - box-shadow
        - filter:progid:DXImageTransform.Microsoft.gradient
        - -ms-filter:\\'progid:DXImageTransform.Microsoft.gradient
        - text-shadow

  property-units:
    - 2
    -
      global: [
        'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
        'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
        'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
        'deg', 'grad', 'rad', 'turn',            # Angle
        'ms', 's',                               # Duration
        'Hz', 'kHz',                             # Frequency
        'dpi', 'dpcm', 'dppx',                   # Resolution
        '%'                                      # Other
      ]
      per-property: {}

  pseudo-element: 2

  quotes:
    - 2
    -
      style: 'single'

  shorthand-values:
    - 2
    -
      allowed-shorthands: [1, 2, 3, 4]

  single-line-per-selector: 2

  space-after-bang:
    - 2
    -
      include: false

  space-after-colon:
    - 2
    -
      include: true

  space-after-comma:
    - 2
    -
      include: true

  space-around-operator:
    - 2
    -
      include: true

  space-before-bang:
    - 2
    -
      include: true

  space-before-brace:
    - 2
    -
      include: true

  space-before-colon:
    - 2
    -
      include: false

  space-between-parens:
    - 2
    -
      include: false

  trailing-semicolon:
    - 2
    -
      include: true

  url-quotes: 2

  variable-for-property:
    - 2
    -
      allow-map-get: true
      allowed-functions: []
      properties: []

  variable-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'

  zero-unit:
    - 2
    -
      include: false
