# File Options
files:
# Rule Configuration
rules:
  # formatting
  quotes: 0
  leading-zero: 0
  space-after-comma: 2
  indentation:
    - 2
    -
      size: 2
  empty-line-between-blocks: 0
  no-css-comments: 0
  space-around-operator: 2
  no-empty-rulesets: 0
  space-after-colon: 2
  space-before-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  url-quotes: 2
  single-line-per-selector: 0
  one-declaration-per-line: 0
  attribute-quotes: 0
  no-trailing-zero: 0
  hex-notation: 0
  trailing-semicolon: 2
  space-between-parens: 2
  hex-length: 0
  brace-style: 0

  # css rules
  property-sort-order: 0
  shorthand-values: 0
  no-important: 0
  no-ids: 0
  no-misspelled-properties: 2
  border-zero: 2
  zero-unit: 2
  no-duplicate-properties: 0
  no-qualifying-elements: 0
  no-transition-all: 0

  # sass rules
  force-element-nesting: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  no-color-literals: 0
  mixins-before-declarations: 2
  extends-before-declarations: 2
  no-vendor-prefixes: 2
  pseudo-element: 0
  no-mergeable-selectors: 0
  placeholder-in-extend: 0
  nesting-depth: 0
  empty-args: 0
  clean-import-paths: 2

  # naming format
  variable-name-format: 0
  class-name-format: 0
  mixin-name-format: 0
